### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by baygeldin** [nats-io/stan.rb#21]
Hi, for some reason I can't connect to the NATS streaming server.

I've launched both NATS server and streaming server locally via Docker:
```
docker run -p 4222:4222 -ti nats:latest
docker run -p 4223:4223 -p 8223:8223 nats-streaming -p 4223 -m 8223
```

Then I tried to connect to it like this:
```
require 'stan/client'

opts = { servers: ["nats://127.0.0.1:4222"] }
sc = STAN::Client.new
sc.connect("test-cluster", "client-pub", nats: opts)
```

But I always get `STAN::ConnectReqTimeoutError (stan: failed connecting to 'test-cluster')`.

I tried publishing messages through `nats-pure` interface and it works fine. I also tried running Go examples from https://github.com/nats-io/stan.go/tree/master/examples and it also worked.

It seems to me like NATS streaming server API has changed since the last commit (or something of this sort), so this gem no longer works. I hope I am wrong, but please let me know if that's the case.

**Comment by ripienaar** [comment]
Try connecting to port 4223. STAN hosts  it’s own nats server.

**Comment by baygeldin** [comment]
> Try connecting to port 4223. STAN hosts it’s own nats server.

Thanks for the info! Now I get `NATS::IO::Timeout (nats: timeout)`. I tried to set `connect_timeout` to 10 seconds, but it didn't work.

**Comment by ripienaar** [comment]
Could be -p is somehow ignored in docker? Don't start the first container at all and only start the streaming one, dont supply `-p` to it and use port 4222.

`telnet` or `nc` test on port 4222 should give you INFO line

**Comment by baygeldin** [comment]
> Could be -p is somehow ignored in docker? Don't start the first container at all and only start the streaming one, dont supply `-p` to it and use port 4222.

I don't think that there's something wrong with Docker setup since Go examples work fine with it. Still, I tried running it like so  `docker run -p 4222:4222 -p 8223:8223 nats-streaming -m 8223` and got the same error.

> `telnet` or `nc` test on port 4222 should give you INFO line

Yes, it does.

**Comment by ripienaar** [comment]
Running the latest nats-streaming-server:

```
$ docker run -p 4222:4222 -p 8223:8223 nats-streaming -m 8223

1] 2020/03/19 12:50:05.940284 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.17.0
1] 2020/03/19 12:50:05.940444 [INF] STREAM: ServerID: Sj6hWxpaw1ivzBuAAzHLIs
1] 2020/03/19 12:50:05.940449 [INF] STREAM: Go version: go1.13.7
1] 2020/03/19 12:50:05.940453 [INF] STREAM: Git commit: [f4b7190]
1] 2020/03/19 12:50:05.941430 [INF] Starting nats-server version 2.1.4
1] 2020/03/19 12:50:05.941437 [INF] Git commit [fb009af]
1] 2020/03/19 12:50:05.941709 [INF] Starting http monitor on 0.0.0.0:8223
1] 2020/03/19 12:50:05.941823 [INF] Listening for client connections on 0.0.0.0:4222
1] 2020/03/19 12:50:05.941841 [INF] Server id is NDRSMIDYHFHHHKKVX63S47GCMRW23KDVA7J7HSUCR2ZA7EUOI6WFKKG5
1] 2020/03/19 12:50:05.941845 [INF] Server is ready
1] 2020/03/19 12:50:05.968679 [INF] STREAM: Recovering the state...
1] 2020/03/19 12:50:05.968707 [INF] STREAM: No recovered state
1] 2020/03/19 12:50:06.219771 [INF] STREAM: Message store is MEMORY
1] 2020/03/19 12:50:06.219860 [INF] STREAM: ---------- Store Limits ----------
1] 2020/03/19 12:50:06.219868 [INF] STREAM: Channels:                  100 *
1] 2020/03/19 12:50:06.219874 [INF] STREAM: --------- Channels Limits --------
1] 2020/03/19 12:50:06.219879 [INF] STREAM:   Subscriptions:          1000 *
1] 2020/03/19 12:50:06.219885 [INF] STREAM:   Messages     :       1000000 *
1] 2020/03/19 12:50:06.219890 [INF] STREAM:   Bytes        :     976.56 MB *
1] 2020/03/19 12:50:06.219896 [INF] STREAM:   Age          :     unlimited *
1] 2020/03/19 12:50:06.219901 [INF] STREAM:   Inactivity   :     unlimited *
1] 2020/03/19 12:50:06.219906 [INF] STREAM: ----------------------------------
1] 2020/03/19 12:50:06.219912 [INF] STREAM: Streaming Server is ready
1] 2020/03/19 12:51:51.389324 [INF] STREAM: Channel "hello" has been created
```

And latest ruby stan client:

```
irb(main):009:0> STAN::VERSION
=> "0.2.2"
```

It works for me:

```
[rip@dev1]% irb                                                                                                                                                                     <13:50:46
irb(main):001:0> require 'stan/client'
=> true
irb(main):002:0> sc = STAN::Client.new
=> #<STAN::Client:0x00000002a90568 ...>
irb(main):003:0> opts = { servers: ["nats://127.0.0.1:4222"] }
=> {:servers=>["nats://127.0.0.1:4222"]}
irb(main):004:0> sc = STAN::Client.new
=> #<STAN::Client:0x00000002aa9e78 ...>
irb(main):005:0> sc.connect("test-cluster", "client-pub", nats: opts)
=> nil
irb(main):006:0> sc.publish("hello", "world")
=> "2e5a48fe02b7685bee53ee"
```

**Comment by baygeldin** [comment]
@ripienaar I... I swear I was executing the exact same commands, but it didn't work and then all of a sudden it did. I feel very stupid now 😅  Anyway, thanks a lot!

**Comment by ripienaar** [comment]
So it goes, I am sure we've all made the same mistakes 100 times before :) good luck.
