### ISSUE TITLE
user/password auth might be botched

### ISSUE THREAD

**Issue by costa** [nats-io/stan.rb#22]
I'm getting a supposedly internal error while trying to connect with user/password — the same setup without user/password actually works:
```
tester_1     |      Failure/Error: stan.connect USER_NATS_CLUSTER_ID, 'tester', nats: {servers: ["nats://#{user}:#{password}@#{USER_NATS_HOST}:#{USER_NATS_PORT}"]}
tester_1     |
tester_1     |      NoMethodError:
tester_1     |        undefined method `<<' for nil:NilClass
tester_1     |      # /usr/local/bundle/gems/nats-pure-0.6.2/lib/nats/io/client.rb:797:in `send_command'
tester_1     |      # /usr/local/bundle/gems/nats-pure-0.6.2/lib/nats/io/client.rb:370:in `subscribe'
tester_1     |      # /usr/local/bundle/gems/nats-streaming-0.2.2/lib/stan/client.rb:139:in `connect'
tester_1     |      # ./integ_spec.rb:66:in `block (3 levels) in <top (required)>'
```
I hope that someone can share a workaround, if any, at least.

**Comment by wallyqs** [comment]
I think you might be getting an authorization error. You could confirm whether this is the case by looking at the NATS Streaming server/NATS Server logs or by using the error callback that can be set on the the NATS client connection as follows:

```ruby
require 'stan/client'

sc = STAN::Client.new
nc = NATS::IO::Client.new

nc.on_error do |e|
  p e
end

# Customize connection to NATS
opts = { servers: ["nats://foo:quux@127.0.0.1:4222"] }
nc.connect(opts)
sc.connect("test-cluster", "client-123", nats: nc)
```

**Comment by costa** [comment]
@wallyqs thanks for your reply
I doubt it gets to the auth stage, as the matter of fact, in that test (i'm building a tiny user mgmt server) I first check the connection without any creds and it fails perfectly with `NATS::IO::AuthError` (and the server logs even show quite a bit of retries), but no matter what credentials I config with the server and the client, I get the error above.

**Comment by costa** [comment]
If there's a test for a user/password auth, I couldn't find it here, that would be excellent.

**Comment by wallyqs** [comment]
Did you get an error using the async callback? Here you can find some of the basic auth tests from the NATS client: https://github.com/nats-io/nats-pure.rb/blob/master/spec/auth_spec.rb

**Comment by costa** [comment]
@wallyqs you see the line that gets the error above in the issue text, `stan` is just `STAN::Client.new`, no callbacks.
Well that is a spec from a dependency, so I don't know, this looks like an internal error (aka bug) and I'm out of ideas. I'm using just `image: nats-streaming:0.14.1` with a couple of users configured, but again, it fails beforehand, the server shows no log lines for my user/password connection attempts, just those without credentials.

**Comment by costa** [comment]
I've got it, it was an internal error alright, but thankfully, that has a workaround. I was just reusing the client object after a failed auth, which was in an invalid state. Consider replacing `new` with `connect` class method and hiding `new` so this situation can be avoided.

**Comment by wallyqs** [comment]
@costa thanks for the feedback, I think you are right on that one re: class connect and would follow closer on what is done in other clients
